apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo
spec:
  ingressClassName: nginx
  tls:
  - hosts:
      - echo.test.hack2022.ch
    secretName: echo  
  rules:
  - host: echo.test.hack2022.ch
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: echo
            port:
              number: 80